*EXAMPLE 'HELLO WORLD' PROGRAM, WRITTEN FOR CP/M V2.X
*
*BDOS CONSTANTS
BDOS    EQU     00005H          ;BDOS CALL ADDR
PSTR    EQU     009H            ;BDOS PRINT STRING PROCEDURE ID
CTERM   EQU     '$'             ;BDOS PRINT STRING CHARACTER TERMINATOR
*CHARACTER CONSTANTS
LF      EQU     00AH            ;LINEFEED CHARACTER
CR      EQU     00DH            ;CARTRIDGE RETURN CHARACTER
*
*CODE START
        ORG     00100H          ;START AT CP/M'S TPA 
START:  LXI     D,MESSAGE       ;LOAD STRING ADDR INTO DE
        MVI     C,PSTR          ;LOAD PRINT STRING PROC ID
        CALL    BDOS            ;PRINT THE STRING TO THE CONSOLE
        RST     0               ;WARM-BOOT CP/M, RETURN TO DOS
*
*DATA START
MESSAGE:                        ;HELLO WORLD MESSAGE
        DB      'HELLO, WORLD!',CR,LF,CTERM
*
*PROGRAM END
        END
